### ISSUE TITLE
Example returns 404

### ISSUE THREAD

**Issue by sobradob** [dgrtwo/gutenbergr#1]
Hi,

Amazing project. However, one of your examples is returning a 404. Perhaps Gutenberg has moved things around.
```
aristotle_books <- gutenberg_works(author == "Aristotle") %>%
  gutenberg_download(meta_fields = "title")


Error in utils::download.file(url, tmp, quiet = TRUE) : 
  cannot open URL 'http://www.gutenberg.lib.md.us/8/4/3/8438/8438.zip'
In addition: Warning message:
In utils::download.file(url, tmp, quiet = TRUE) :
  cannot open: HTTP status was '404 Not Found'
```

**Comment by dgrtwo** [comment]
Thanks! I think I may have fixed the error, though I wasn't quite able to reproduce it myself. Could you try again with the dev version from

    devtools::install_github("dgrtwo/gutenbergr")

Thanks!

**Comment by sobradob** [comment]
It works!
